### ISSUE TITLE
app not working with Samsung Galaxy J3 2016?

### ISSUE THREAD

**Issue by doctor-M** [johnzweng/SMSSentTime#1]
I have a Samsung Galaxy J3 2016, downloaded and installed the app, app is enabled but it is now working. Any ideas why?

**Comment by johnzweng** [comment]
Writing the SMS database is not possible anymore since Android 4 (only for the default SMS app). I wrote some infos about the topic in general here: http://forum.xda-developers.com/showthread.php?p=51414758#post51414758
